---
- name: Pre-configurations
  hosts: switches
  gather_facts: no
  tasks:
    - name: enable scp
      cisco.ios.ios_config:
        lines:
        - ip scp server enable
    - name: enable archive feature
      cisco.ios.ios_config:
        lines:
        - archive
    - name: enable archive path
      cisco.ios.ios_config:
        lines:
        - path flash:archive
        parents: archive

- name: Test NAPALM on IOS (SW1)
  hosts: sw1
  tasks:
    - name: Config Replace on SW1
      napalm_install_config:
        hostname: sw1
        username: "{{ ansible_user }}"
        password: "{{ ansible_ssh_pass }}"
        dev_os: "{{ ansible_network_os }}"
        config_file: playbooks/configurations/napalm-configs/sw1.conf #should be ran from Ansible-Github directory
        commit_changes: True
        replace_config: True
        diff_file: playbooks/configurations/napalm-diffs/sw1.diff #should be ran from Ansible-Github directory

# - name: Test NAPALM on IOS (SW2)
#   hosts: sw2
#   tasks:
#     - name: Config Replace on SW2
#       napalm.napalm.napalm_install_config:
#             hostname: sw2
#             username: "{{ ansible_user }}"
#             password: "{{ ansible_ssh_pass }}"
#             dev_os: "{{ ansible_network_os }}"
#             config_file: $HOME/github/Ansible-Github/playbooks/ios/sw2.conf
#             commit_changes: True
#             replace_config: True
#             diff_file: sw2.diff